### ISSUE TITLE
add exported = true or false to fix merged manifest in Android 12 up

### ISSUE THREAD

**Issue by antranvn** [ParkSangGwon/TedImagePicker#102]
add exported = true or false to fix merged manifest in Android 12 up

**Comment by ted-prnd** [comment]
What do you mean?
`TedImagePickerContentProvider, FileProvider` already has `export` property
Pleas check [Manifest](https://github.com/ParkSangGwon/TedImagePicker/blob/master/tedimagepicker/src/main/AndroidManifest.xml)
