### ISSUE TITLE
Currently there is no way for the caller of this library to handle the scenario when the Storage permission request is denied

### ISSUE THREAD

**Issue by ebhsgit** [ParkSangGwon/TedImagePicker#110]
Example invoking code

```
        TedImagePicker.Builder builder = TedImagePicker.with(this.cordova.getContext())
                .showCameraTile(showCameraTile)
                .showTitle(showTitle)
                .zoomIndicator(zoomIndicator)
                .errorListener(error -> {
                       // Handle error
                })
                .cancelListener(() -> {
                       // Handle cancel
                });

       builder.start(result -> {
                       // Handle result
            });
```

The caller of this code would wait for the outcome of the user action to `pick an image`.
The expected outcome would be one of the 3 handlers (error, cancel, or result).

However, if the user denies the permission request, none of the 3 handlers are called.

----

Personally, I was expected an error to be thrown.
It can be seen that in [TedImagePickerBaseBuilder line 102](https://github.com/ParkSangGwon/TedImagePicker/blob/master/tedimagepicker/src/main/java/gun0912/tedimagepicker/builder/TedImagePickerBaseBuilder.kt#L102) the denied scenario is not handled

**Comment by ted-prnd** [comment]
@ebhsgit 
If you want check permission deny, you have to request permission by your code.
[TedPermission](https://github.com/ParkSangGwon/TedPermission) will help check permission

**Comment by ebhsgit** [comment]
Thanks for clarifying.
That's exactly what I've done to work around this situation.

-----

That said, I would still expect to get a permission error.
Because as it stands right now, if the calling code does not check for permissions first, and the user denies the permissions, then the calling code waiting indefinitely.

Food for thought. Ultimately, the decision is yours.
Great package by the way 👍
