### ISSUE TITLE
TedImagePicker not opens in Android OS 13 api level 33

### ISSUE THREAD

**Issue by ArunJsn** [ParkSangGwon/TedImagePicker#126]

**Comment by ParkSangGwon** [comment]
@ArunJsn 
Did you test demo project?
Or please let me know error message

**Comment by vordor** [comment]
android 13이상에서는 WRITE_EXTERNAL_STORAGE가 필요없는데 WRITE_EXTERNAL_STORAGE 퍼미션 설정이 되어있어서 에러가 발생하는 거에요

**Comment by vordor** [comment]
TedBottomPicker도 동일한 문제입니다

**Comment by ParkSangGwon** [comment]
same issue https://github.com/ParkSangGwon/TedImagePicker/issues/122
