### ISSUE TITLE
Disable select picture from gallery

### ISSUE THREAD

**Issue by WaOnEmperoR** [ParkSangGwon/TedImagePicker#17]
Hi, I have a requirement where user can only take multiple image from camera. Not gallery. So, the gallery must be disabled. How to achieve such things? I previously used your TedPicker library and I'm able to do that. But since TedPicker has an issue with cwac-camera, I must upgrade to TedImagePicker.

**Comment by ParkSangGwon** [comment]
@WaOnEmperoR 
I can not understand your request.
If you don't want gallery, you don't need this library

**Comment by WaOnEmperoR** [comment]
Hi thanks for your reply.

I'm sorry if my request is biased, Gallery I mean is the internal storage, hence we can only take picture from camera.

By the way I'm able to do implement this requirement by myself. Just commenting out the line 75 and 76 of your GalleryAdapter.java.

`//            cursor = context.getApplicationContext().getContentResolver().query(uri, columns, null, null, orderBy);
//            imageCursor = sContext.getContentResolver().query(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, columns, null, null, orderBy);
` 

thanks for your amazing library
