### ISSUE TITLE
다중선택시 숫자배경색 커스텀 가능할까요..?

### ISSUE THREAD

**Issue by Chanooo** [ParkSangGwon/TedImagePicker#18]
안녕하세요 TedImagePicker개발자님! 다름이 아니라, 이미지 다중 선택시 이미지 우측 상단에 생기는 숫자 배경색이랑  맨 아래 전체보기 오른쪽 숫자 색을 커스텀 할 수 있도록 함수 추가해주실 수 있으신가요..  현존하는 이미지픽커중에 가장 예쁘고 좋은 것 같습니다.  좋은 이미지피커 만들어주셔서 진심으로 감사드립니다.

**Comment by ParkSangGwon** [comment]
@Chanooo 
사용하시는 프로젝트의 colors.xml에 아래 color값을 추가하시고 원하는 색상으로 처리하시면 됩니다.
```xml
<color name="ted_image_picker_primary">#your_color_code</color>
<color name="ted_image_picker_primary_pressed">#your_color_code</color>
```
