### ISSUE TITLE
Need to start image picker with previously selected image

### ISSUE THREAD

**Issue by neetrath** [ParkSangGwon/TedImagePicker#2]
Example scenario
1. I press the button to pick some images
2. Press the "Done" button. It will go back to the previous screen.
3. I press the button to pick images again. >> None of the images is selected.

I want to start image picker with the previously selected image in step 3

**Comment by ParkSangGwon** [comment]
@neetrath 
Please read [this](https://github.com/ParkSangGwon/TedImagePicker#multi-select)
You have to use `selectedUri()`
