### ISSUE TITLE
Content Uri on Android 11

### ISSUE THREAD

**Issue by DevAdeel** [ParkSangGwon/TedImagePicker#67]
Android 11 return content uri instead of file path.

**Comment by SQadami** [comment]
Adding android:requestLegacyExternalStorage="true" to the manifest's application block

and convert result Uri: 

    public static Uri pathUri(Uri uri) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            String[] filePathColumn = {MediaStore.MediaColumns.DATA};
            Cursor cursor = ShopperApp.getContext().getContentResolver().query(
                    uri,
                    filePathColumn,
                    null,
                    null,
                    null);
            if (cursor != null) {
                if (cursor.moveToFirst()) {
                    int columnIndex = cursor.getColumnIndex(filePathColumn[0]);
                    String absolutePathOfImage = cursor.getString(columnIndex);
                    if (absolutePathOfImage != null) {
                        return Uri.parse(absolutePathOfImage);
                    }
                    cursor.close();
                }
            }
        }

        return uri;
    }

**Comment by DevAdeel** [comment]
> Adding android:requestLegacyExternalStorage="true" to the manifest's application block
> 
> and convert result Uri:
> 
> ```
> public static Uri pathUri(Uri uri) {
>     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
>         String[] filePathColumn = {MediaStore.MediaColumns.DATA};
>         Cursor cursor = ShopperApp.getContext().getContentResolver().query(
>                 uri,
>                 filePathColumn,
>                 null,
>                 null,
>                 null);
>         if (cursor != null) {
>             if (cursor.moveToFirst()) {
>                 int columnIndex = cursor.getColumnIndex(filePathColumn[0]);
>                 String absolutePathOfImage = cursor.getString(columnIndex);
>                 if (absolutePathOfImage != null) {
>                     return Uri.parse(absolutePathOfImage);
>                 }
>                 cursor.close();
>             }
>         }
>     }
> 
>     return uri;
> }
> ```

MediaStore.MediaColumns.DATA is also deprecated as of API level 30

**Comment by pvnhat** [comment]
android:requestLegacyExternalStorage="true" is ignored on Android 11. 
refer: https://developer.android.com/training/data-storage/use-cases
![image](https://user-images.githubusercontent.com/40590894/117903098-20b0f180-b2f9-11eb-8a48-6af35dead168.png)

**Comment by ParkSangGwon** [comment]
I think if you can use recent version, you can resolve this issue
If this issue not resolved, please let me know
