### ISSUE TITLE
Migration to mavenCentral

### ISSUE THREAD

**Issue by praveenrajput** [ParkSangGwon/TedImagePicker#72]
Completely removing jCenter from the project, leads to the build error of `gun0912.ted:tedpermission-rx2` and `gun0912.ted:tedonactivityresult-rx2` dependencies not found at mavenCentral.

Although adding `jCenter()` to repositories fixes the issue, but please migrate these two dependencies to the mavenCentral too, as jCenter is at EOL.

**Comment by EinfachHans** [comment]
+1

**Comment by contfedorov** [comment]
+3

**Comment by ParkSangGwon** [comment]
You can use mavenCentral() !!!
