### ISSUE TITLE
Feature Request: Audio

### ISSUE THREAD

**Issue by Marcosmaliki** [ParkSangGwon/TedImagePicker#8]
Please add support for audio media type
Great library though, thank you.

**Comment by ParkSangGwon** [comment]
@Marcosmaliki 
Yes, we can support audio media type. `MediaStore` have `AUDIO`type.
But I decided not to supoprt AUDIO` type even if it supports.
Because this library is *TedImagePicker*.
Thanks about your request, but I think you have to find another audio library
